### ISSUE TITLE
Spelling and grammar

### ISSUE THREAD

**Issue by yuvi3000** [andreshazard/Telegram-PokeBotGo#5]
1) /type function returns 

> Week Against:

Instead of 

> Weak Against:

2) /start function returns 

> Please use one of the command follow by a valid parameter

 instead of 

> Please use one of the commands, followed by a valid parameter

**Comment by andreshazard** [comment]
@yuvi3000 This has been fixed.

**Comment by yuvi3000** [comment]
Great!

Tiny edit, though.

The /start function still shows this:

> Hi trainer.
> Use one of the commands follow by a parameter to get information.

Instead of

"Hi, trainer!
Use one of the commands followed by a parameter to get information."
